languages:
  JavaScript: true
  Ruby: true
  Python: false
  PHP: false

exclude_patterns:
- tests/**/*
- node_modules/**/*

plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true

version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
