env:
  global:
  - CC_TEST_REPORTER_ID=2c0263d0730edc77654195955e1221cbfad01a4f3010dab476c3917769236fe2
  - GITHUB_REPO: proustibat/svg-loader-es6
language: node_js
node_js:
- '8'
- '10'
cache: yarn
addons:
  sonarcloud:
    organization: proustibat-github
    token:
      secure: "Q50ZQV/l4rdGz4O0er3fH6lL8M1W2SunpOwNhUn/IUxfUGRpb+95tYUld8sxLI6t71YgzhnmwdWzTc7rxTERb7TTkNBnvQUlmIV9WOgC5UDf5vVilsVcELXI7Z69vf6H2ULU0KnKInrb1tX0jeBkqs5+I5Z8aF40qWT+5kPMtdgqLw1Gm0eGHt3+u9YmtSXghuWfWioEQ4w74KZB2RR9WRRbJzV3tPetK2DyU0NK82MwJzisST46+Jwx4XVn5ZB/PZVA/Z5/6vwd1DV1foUvlV+HJhSjv44NK67cKc78iLS5ZX82XIyJJazk3DbhN28TJdP63vORp3TdD8gCJI6ImpqJoNu2v0SgdAJnQ7dTbabOTSuNxIkXiywEPqa+PveTU4dtO/ULxVfIHqVEfCQD4EoHINO2jQXOg1pfiRQkmB4ibnDzDAQF6cnuybb/LEVI53rJQmVKm99nUVx6k/6wvp5Y1u8u7s1gIEK7AIakkA9ZSdqOsGOjCZdGCSndtinqh3164O0vaP3L7V6uKipFWmoo4/J0ERWs0WznkX5ZAnV0YZmnEJxV9kixEBEHlz38Ln7ARCb9mA57Z24Ku7vf/OBxIaSUxXWXlLrP+YmTlqQTo2ndvdMofCTULddvnxkKmVE39f+XiMoNBE/9ok0AnvRu+ET5eO/8U80enQEfdr8="

install:
- yarn install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn lint:js && bash sonar.sh
